version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-triage-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sreue9ixeei5"
s3_prefix = "serverless-triage-api"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
